### ISSUE TITLE
[Bug] Loot counter on biker heist

### ISSUE THREAD

**Issue by LT71** [MiamiCenterPL/VoidUI-InfoBoxes#4]
**Describe the bug**
Hello i noticed a possible bug on biker heist day 2 with the loot counter. It doesn't seem to count weapon cases and the helmet for me until the containers have been opened. It's the possible loot counter im referring to.

**To Reproduce**
1. Go to biker heist day 2
2. Check the counter for possible loot

**Expected behavior**
Expect to see the possible loot for the weapon cases and the bsi helmet.

**Comment by MiamiCenterPL** [comment]
It is possible that heist was constructed that way. My mod does only count loot that player can interact with at any time, since a lot of stuff in game is random, for instance - loot crate - it spawns loot (or not) in the exact second that players opens the container. There's no way of knowing beforehand what, and even if the crate will spawn loot.

Although, I will check this heist manually and see if there's something I can improve with the loot counting.

**Comment by LT71** [comment]
It might be a special case because some of the weapon cases are inside a wooden crate so you need to open the crate to be able to open the weapon box. But I think it's weird that the weapon crates in front of the train aren't counted since they always spawn on the ground in the cage. 

I thought that the BCI helmet might be its own crate interaction since it only exists as far as I know on this heist.

**Comment by MiamiCenterPL** [comment]
I need to check the Mission Script since it all probably is dependent on difficulty.
The Helmet is not counted at all iirc., and that's something I can surely improve.
I will check it all on monday since I am on a small vacations now (Visiting Kraków, Poland)

**Comment by LT71** [comment]
Okay, I'll check some more heists if I can find any more missing loot. Enjoy your vacation :)

**Comment by MiamiCenterPL** [comment]
This should be fixed now. The Biker's heist units are weird because they don't have the carry_id while my script is checking them, and that was causing the weapons and Helmet to not count towards the Loot / Possible Loot counters.
